# Generated by Django 3.2.12 on 2022-03-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_news", "0003_auto_20220325_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="api_news.post",
            ),
        ),
    ]
